from enum import Enum


class EventType(str, Enum):
    """
    Events RescueMesh currently knows how to respond to.
    """

    # Normal lifecycle
    DONATION_CREATED = "DONATION_CREATED"
    DRIVER_ACCEPTED = "DRIVER_ACCEPTED"
    PICKUP_COMPLETED = "PICKUP_COMPLETED"
    DELIVERY_COMPLETED = "DELIVERY_COMPLETED"
    PANTRY_RECEIVED = "PANTRY_RECEIVED"

    # Disruptions
    DRIVER_CANCELLED = "DRIVER_CANCELLED"
    PANTRY_CAPACITY_CHANGED = "PANTRY_CAPACITY_CHANGED"
    PANTRY_CLOSED = "PANTRY_CLOSED"
    DELIVERY_FAILED = "DELIVERY_FAILED"
    DONATION_EXPIRED = "DONATION_EXPIRED"


SUPPORTED_EVENT_TYPES = {
    event.value
    for event in EventType
}